db:
  type: mysql
user_table: xx
spring:
  application:
    name: learn-flyway
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  flyway:
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建history表
    baseline-on-migrate: true
    baseline-version: 6.2
    baseline-description: "xxx -> << Flyway Baseline >>"
#    init-sqls:
#      - create table t_xxx(id int primary key auto_increment);
    validate-migration-naming: true
    # 使用的数据库，默认为连接上的，大小写敏感
    schemas: flyway,flyway2
    placeholders:
      user_table: t_user
      aaa: zs
      placeholder_or_environment: dev # 注释的配置解析需要，太拉胯了
    table: flyway_schema_history_${spring.application.name}
    # 启动、校验失败时清空数据库，生产时需要禁用！！！！！！！！！！！
#    clean-disabled: false
#    clean-on-validation-error: true
    script-placeholder-prefix: FP__
    script-placeholder-suffix: __
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: "classpath:db/migration/${db.type}"
    ################################################################################################################
    # 是否启用flyway
    enabled: true
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径不存在时是否报错
    fail-on-missing-locations: false
    # 迁移sql脚本文件名称的前缀
    sql-migration-prefix: "V"
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: ".sql,.abc"
    # 迁移sql脚本文件名称的分隔符
    sql-migration-separator: "__"
    # 可重复执行的文件前缀
    repeatable-sql-migration-prefix: "R"
    # 迁移时是否进行校验
    validate-on-migrate: true
    # sql脚本内可使用占位符功能
    placeholder-prefix: "${"
    placeholder-separator: ":"
    placeholder-suffix: "}"
    placeholder-replacement: true
    create-schemas: true
    ################################################################################################################
    # 默认连接使用的表空间
    # tablespace:
    # 迁移到的目标版本
    # target:
    # 记录迁移的执行人
    installed-by: admin
    # 默认使用 spring.datasource 下的配置
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/flyway?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    # user: root
    # password: root
#    batch: true # team专有
#    dry-run-output: C:\Users\admin\Desktop\dryOutOutput.txt # team专有
#    jdbc-properties: # team专有，参数传递给jdbc驱动
#      aaa: xxx
#    # team专有，output a table with the results of queries when executing migrations
#    output-query-results: true
#    # team专有，skip executing the contents of the migrations and only update the schema history table
#    skip-executing-migrations: false
#    # team专有，automatically detect SQL migration file encoding
#    detect-encoding: true
